server:
  port: 8888
spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  application:
    name: config-service-dev
    
---
spring:
  profiles: test
  application:
    name: config-service-test
